### ISSUE TITLE
Incorrect Fonts

### ISSUE THREAD

**Issue by vicadam** [Codeinwp/flat#49]
After updating from 1.3.7 or 1.3.8 (can't remember) to 1.4.3, the fonts are not displaying correctly. For example, the header is set to Open Sans condensed, but displays something different:
![font_err](https://cloud.githubusercontent.com/assets/2036925/4153324/827fb40a-3457-11e4-8526-df765b4c9d8c.jpg)

**Comment by thanhluu** [comment]
@vicadam is this fine now? I have changed the way to included fonts on the last commit.

**Comment by marlosirapuan** [comment]
same problem with me..

**Comment by victorperin** [comment]
It seems to be fixed now, any other person with this problem in the latest version?
