### ISSUE TITLE
Adding logo has no effet

### ISSUE THREAD

**Issue by gaetan-petit** [Codeinwp/flat#66]
**Version**: 1.5.4
**Description**:
Adding a logo in the customization menu has no effect (the logo is not displayed anywhere on the page)

**Comment by gaetan-petit** [comment]
Hey @thanhluu do you need any informations or help with this ?

**Comment by victorperin** [comment]
Hi @gaetan-petit! Informations are every time wellcome!
When I get some time, I'll try to fix it!

**Comment by thanhluu** [comment]
@gaetan-petit : Please update to the 1.5.5 and give me a screenshot for further checking. @victorperin Can you check this issue?

**Comment by victorperin** [comment]
Tested on 1.5.5 and the issue keep opened...
Trying to make it work again

**Comment by victorperin** [comment]
Bug found! As a matter of fact, there's the option "Display as" that can choose if will use "Site title", "Site Logo" or "Both Title & Logo".
@thanhluu I could make a function that detect it and removing that option.

**Comment by victorperin** [comment]
:+1:
