### ISSUE TITLE
Footer is broken in IE11

### ISSUE THREAD

**Issue by k4kfh** [Codeinwp/flat#87]
Apparently IE11 doesn't support the <footer> element, and for whatever reason the footer ends up moving with the end of the animated menu, instead of just sitting at the bottom of the page like it's supposed to. Please fix this ASAP! Other than that, great theme, I love it!

**Comment by SamPlusPlus** [comment]
I am also experiencing this issue in IE11. I am happy to give what ever info I can to get this solved. I would love to switch my site to this theme.
